### ISSUE TITLE
on Windows setuptools.find_packages in setup.py fails due to unsupported path specification

### ISSUE THREAD

**Issue by konstan** [nuvla/python-library#28]
https://github.com/nuvla/python-library/blob/master/code/setup.py#L12

```
WARNING: Discarding https://files.pythonhosted.org/packages/c2/5b/2b3dde74f437485ed9e14c163b4691deaa2ecc54694acdd0fe2ddd0cd416/nuvla-api-0.0.3.tar.gz#sha256=3c426928f92bf097895d5ee1c4408366802365b92456d25b5db7309f6739f487 (from https://pypi.org/simple/nuvla-api/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached nuvla-api-0.0.2.tar.gz (6.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\users\XXX\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXX\\AppData\\Local\\Temp\\pip-install-ck1q5g19\\nuvla-api_6107fbab55174fd9961a60b2c151b18b\\setup.py'"'"'; __file__='"'"'C:\\Users\\XXX\\AppData\\Local\\Temp\\pip-install-ck1q5g19\\nuvla-api_6107fbab55174fd9961a60b2c151b18b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\XXX\AppData\Local\Temp\pip-pip-egg-info-xldelthd'
         cwd: C:\Users\XXX\AppData\Local\Temp\pip-install-ck1q5g19\nuvla-api_6107fbab55174fd9961a60b2c151b18b\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXX\AppData\Local\Temp\pip-install-ck1q5g19\nuvla-api_6107fbab55174fd9961a60b2c151b18b\setup.py", line 16, in <module>
        packages = find_packages(where='src/')
      File "C:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\users\XXXX\appdata\local\programs\python\python39\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/' cannot end with '/'
```

**Comment by konstan** [comment]
In fact, https://github.com/nuvla/python-library/blob/master/code/setup.py#L12 is redundant as https://github.com/nuvla/python-library/blob/master/code/setup.py#L23 is used instead.
